<img src=https://courseware.decoded.com/images/decoded/logo-decoded.png align=left width=100px/>

# Python: Data Processing

---

<small>© COPYRIGHT 2026 DECODED LIMITED. ALL RIGHTS RESERVED. Web: https://decoded.com/ </small>

## Learning Objectives


1. **Data types** Data types in python
1. **ETL Mastery:** Ingest "wild" data formats (CSV with bad delimiters, Excel with metadata headers).
2. **Data Hygiene:** Apply a Standard Operating Procedure (SOP) to fix data types and missing values.



---

## Instructor Overview

THIS SECTION WILL NOT BE LEARNER FACING


### Programmes

* Workshop 1.1 - Data Science Accelerator


### Module Summary

In this module, we transition from basic Python scripting to professional data science practices. We acknowledge that "Happy Path" programming—where data is always clean and properly formatted—is a myth in the real world.

You will learn to function as a data engineer by mastering the ETL (Extract, Transform, Load) pipeline. We start by ingesting "wild" data formats, tackling common pain points like bad delimiters, metadata headers in Excel, and nested JSON structures.

Crucially, we establish a Standard Operating Procedure (SOP) for data hygiene to prevent "silent failures" caused by hidden data type errors (the "Object Trap") and missing values. By the end of this session, you will be able to robustly ingest, clean, and validate messy datasets, ensuring they are ready for downstream analysis.



### Prerequisite Questions

See [Menti](https://www.mentimeter.com/app/presentation/alnn25pb2gusirfj3w7x8gihks2d5yux/cxq6xun9b18i/edit),

1. How comfortable are you with using:
    - Python
    - Jupyter notebooks
    - Keyboard shortcuts


2. How comfortable are you with Python:
    - Lists
    - Dictionaries
    - Tuples
    - Loops
    
    
3. What is a variable?
    

4. How do you assign variables in Python?
    - =
    - ==
    - !=
    - ->
    - <-
    
    
5. How do index elements of a list or string in Python?
    - ()
    - []
    - {}
    
    
6. What is a `for-loop` vs a `while-loop`?


7. What are you looking to get out of the session?


### Instructor Resources

* [Slides](xxx)
* [Menti](https://www.mentimeter.com/app/presentation/alnn25pb2gusirfj3w7x8gihks2d5yux/cxq6xun9b18i/edit)
* [Pre-workshop online material](xxx)
* [Learner facing workshop cheat sheet](xxx)
* [Learner facing challenges](xxx)
* [Learner facing challenge solutions](xxx)
* [Format String Syntax - Python Documentation](https://docs.python.org/3/library/string.html#formatstrings)
* [Feedback link](xxx)


---

## Content

### Overview

    
*   Introductions
    *   Purpose: What is the aim of the content?    
    *   Objectives: What will I learn?
    *   Process: How will I learn this content?
    *   Expectations: Am I right for this content?
    *   Applications: Why study this?
*   How do you define complex datasets with collections?
    *   How do I create an use lists of data?
    *   How do I create and use data relationships?
    *   How do I create an used immutable lists of data?
    *   Challenge: Analyse complex data sets
*   How do you analyse complex datasets with loops?
    *   Why repeat code?
    *   What types of loops are there in Python?
    *   Challenge: Modify a `for`-loop to `print()` the elements of a list
    *   Stretch Challenge: Compute aggregate statistics from lists of data
* An introduction to numpy and pandas
    *  Understanding the difference between a list, an array, and a DataFrame
    *  Challenge: Compare `numpy` arrays with python `lists`
* What is a `numpy` array?
    *  Introduce to n-dimensional arrays as efficient grids of values
    *  Challenge: Create a numpy array with `np.array` and get its `.shape`
* What is a `pandas` DataFrame?
    * How to create tabular data structures from dictionaries and lists
    * Challenge: Compare a DataFrame with an array
* How do you extract raw datasets into python?
    * How do you handle "wild" csvs ?
    * How do you address common pain points found in importing Excel spreadsheets?
    * How do you load complex JSON structures?
    * Challenge: Clean dataset    
* How do you keep you data hygienic in Python?
    * How do you perform health check on your data in Python ?
    * How do you enforce the data type in Python?
    * How do you detect and impute missing values?
    * Challenge: Clean dataset    
* Review
    *   What did we learn?
    *   What should I learn next?

#### Process: How will I learn this content?

##### Outline

- Menti quiz
- Group discussions
- Coding demos
- Coding challenges

TEACHER NOTES

#### Expectations: Am I right for this content?

Teacher link to [Menti](https://www.mentimeter.com/app/presentation/alnn25pb2gusirfj3w7x8gihks2d5yux/cxq6xun9b18i/edit)

#### Menti

[www.menti.com](www.menti.com)

### Applications: Why study Data Processing in Python?

Data has become ubiquitous and a diverse range of tasks and problems require data to be performed and solved.

This can vary enormously, from developing a website, creating an analytical report, writing an application for a phone, or creating an AI model. All require data to be sourced, engineered, processed and consumed.

Python is an increasingly popular programming language for processing data efficiently.

---

### How do you define complex datasets with collections?

TEACHER NOTES

Explain that collections are built-in Python data structures that allow us to store and manipulate data such as, lists, dictionaries, tuples and sets.

#### How do I create and use lists of data?

`list`s are ordered and mutable (editable) collections of data, can have duplicates.

They are defined with square brackets e.g.,

```python
prices = ["£1.00", 1.50, None, False, 0, ...]
```

Methods on `list`s include, `.append`,

```python
prices.append(1) # prices is mutable
```

...which illustrates that we can modify them.

To create a list we use square brackets,

In [ ]:
locations = ["London", "Leeds", "Manchester"]

As with strings, the first element is at index `0`,

In [ ]:
locations[0]

'London'

We can add additional elements to a `list` with `.append`,

In [ ]:
locations.append('York')
locations

['London', 'Leeds', 'Manchester', 'York']

Or, to add multiple elements, we can use `.extend`,

In [ ]:
locations.extend(['Newcastle','Liverpool', 'York'])
locations

['London', 'Leeds', 'Manchester', 'York', 'Newcastle', 'Liverpool', 'York']

#### How do I create and use data relationships?

A `dict` is a set of *pairs*.

Where a `list` is a sequence of single elements, in a `dict` each element is a `key:value` pair.

These pairs are effectively a *relationship* between the keys and values.

Defined with curly braces with a comma separating paired (`k:v`) elements, e.g.,

```python
record = {"company": "example", "address": ("London", "UK"), "is_open": False, ...}

record["company"] = "Example LTD." # record is mutable
```

As a technical definition, `dict`s are unordered and mutable collections of data stored in key-value pairs, where the keys must be unique.

In [ ]:
city_record = {
    "name": "London",
    "country": "UK",
    "population": 60_000_000
}

We access the entires of the dictionary using the *keys*,

In [ ]:
city_record["population"]

60000000

When the keys of a dictionary do little more than "tag" data, they are effectively *records*, as with `city_record`.

But they can be use to *associate* different types of data,

In [ ]:
classroom_register = {
    "Sherlock": True,
    "Watson": True,
    "Santa Clause": False
}

Did Sherlock turn up to school today?

In [ ]:
classroom_register["Sherlock"]

True

We can add keys to existing dictionaries, one at a time,

In [ ]:
city_record["country"] = "UK"
city_record["continent"] = "EU"

In [ ]:
city_record

{'name': 'London', 'country': 'UK', 'population': 60000000, 'continent': 'EU'}

Or several at once,

In [ ]:
classroom_register.update({
    "Hansle": True,
    "Grettle": True,
    "Witch": False
})

In [ ]:
classroom_register

{'Sherlock': True,
 'Watson': True,
 'Santa Clause': False,
 'Hansle': True,
 'Grettle': True,
 'Witch': False}

A recent addition to python, the `|` operator on dictionaries allows you to create a new dictionary rather than *update* an existing one,

In [ ]:
my_register = classroom_register | {'Michael': True}

In [ ]:
'Michael' in my_register

True

In [ ]:
'Michael' in classroom_register

False

### How do I create an used immutable lists of data?

`tuple`s are ordered and immutable collections of data, which can have duplicates.

Often defined with parentheses, e.g.
```python
address = ("London", "UK", ...)
```

but, only *a comma* is actually required,

```python
city = "London", "UK"
```

`tuple`'s main feature is their immutability (they cannot be modified),
```python
# ERROR: address[0] = "Leeds" # NOT ALLOWED, immutable
```

`tuple`s are simple ways of representing rows of data, which we almost never wish to change.

Consider the `list` below called `table` which contains `tuple`s.

We can `.append` an additional `tuple` to the `list` (because *it* is mutable), but we cannot modify it's elements,

In [ ]:
table = [
    [1, "Alice", "UK"],
    [2, "Eve", "FR"],
]

table.append( [3, "Bob", "US"] )

To access `Alice` we first index to obtain the first entry in `table`, which is index `[0]` and then the second entry in that `tuple`, ie., index `[1]`,

In [ ]:
table[0][1]

'Alice'

In [ ]:
table[0][1] = 'Alison'

#### Challenge: Analyse complex data sets

Consider the following `list` and `dict`ionary definitions,


```python

cities = ["London", "Paris", "New York"]

city_reviews = {
    "London": 4.5,
    "Paris": 4.6,
    "New York": 4.4
}
```

* How many entires are in each dataset?
    * HINT: use `len()`
* What is the first and last entry in `cities`?
    * HINT: index `[0]` and index `[-1]`
* What is the rating for `London` ?
    * HINT: index `["London"]`

Define a variable, `chosen_city = "Paris"`.

* What is the rating for that city? `print()` the city and its rating
    * HINT: index `[chosen_city]`

In [ ]:
# SOLUTION (NOTES)

cities = ["London", "Paris", "New York"]

city_reviews = {
    "London": 4.5,
    "Paris": 4.6,
    "New York": 4.4
}

# How many entires are in each dataset?
print(len(cities))
print(len(city_reviews))

# What is the first and last entry in cities?
print(cities[0])
print(cities[-1])

# What is the rating for London ?
print(city_reviews["London"])

# Define a variable, chosen_city = "Paris".
chosen_city = "Paris"

# What is the rating for that city? print() the city and its rating
print(chosen_city, city_reviews[chosen_city])

3
3
London
New York
4.5
Paris 4.6

---

### How do you analyse complex datasets with loops?

#### Why repeat code?
Simple, or scalar, data is the kind which is only a single value.

Complex, aggregate, or composite data has several parts or elements.

A collection is a group of several separate pieces of data which often need to be processed the same way.

Consider the `prices` collection below. We display each element converted to a USD price (supposing a `1.3x` conversion ratio).

Each element of `prices` is processed the same way, so that two lines of code are repeated,

In [ ]:
prices = [2, 4, 5]

price = prices[0]
usd_price = 1.3 * price
print(usd_price)

price = prices[1]
usd_price = 1.3 * price
print(usd_price)

price = prices[2]
usd_price = 1.3 * price
print(usd_price)

2.6
5.2
6.5

We can simplify this with a for-loop, which repeats the (indented) *body* for each element in an existing dataset,

In [ ]:
for price in prices:
    usd_price = 1.3 * price
    print(usd_price)

2.6
5.2
6.5

Loops also handle the case where we don't know how many elements a collection has, or how often we need to repeat some code.

#### What types of loops are there in Python?

There are two types of loops in Python used to repeat commands, `for`-loops and `while`-loops.

For loops will continue to run until they reach the end of the sequence, whereas while loops will stop running when some condition is met.

Syntax for `for` loops:

```python
for <element label> in <sequence>:
    <some action>
```


Syntax for `while` loops:

```python
while <some condition>:
    <some action>
```

#### Modify a `for`-loop to `print()` the elements of a list

Consider the code example below,


```python
names = ["Sherlock", "Watson", "Irene"]
total = 0

for n in names:
    ...
```

* By replacing `...`, `print()` each name in the list
    * HINT: `n` is the name we've given to each element
* `n` is just a label (, variable), change `n` to `name`
    * HINT: change it in the `for` line and the `print()`
* Update `total` to the total length of all the characters in all the `names`
    * HINT: `+= len(...)`
* Define a list, called `cities`, and `print()` each using a `for`-loop
    * The cities should be `"Paris", "London", "New York"`
    * HINT: you can use any label for the element, call it `city`
* `.append()` each `city` to your `names` list
    * HINT: `names.append(...)`

In [ ]:
# SOLUTION (NOTES)
cities = ["Paris", "London", "New York"]
names  = ["Sherlock", "Watson", "Irene"]

total  = 0

for name in names:
    print(name)
    total += len(name)

for city in cities:
    print(city)
    names.append(city)

Sherlock
Watson
Irene
Paris
London
New York

In [ ]:
# AUTOGRADER (SKIP)

names_correct =  ["Sherlock", "Watson", "Irene"] + ["Paris", "London", "New York"]
total_correct = sum(map(len, names_correct[:3]))

assert total == total_correct           , f"Mistake: Your `total` is wrong, it should be {total_correct}"
assert 'name' in locals()               , f"Mistake: Your looping variable should be called `name`"
assert 'city' in locals()               , f"Mistake: Your looping variable should be called `city`"
assert len(names) == len(names_correct) , f"Mistake: Your `names` are wrong, they should include your `cities`"
assert names == names_correct           , f"Mistake: Your `names` are wrong, they should be exactly `{names_correct}`"

#### Challenge: Compute aggregate statistics from lists of data

Consider the following counts of cookies sold over a week at a bakery,

```python
cookies = [50,64,45,57,60,84,90]
```

* Using a `for` loop,
    * compute the total number of cookies sold, call it `cookie_total`
    * find the minimum sold, call it `cookie_min`
        * HINT: start by guessing that the first is the minimum: `cookie_min = cookies[0]`
        * HINT: compare each element to your guess
            
* When done, add the following `cookie_report` to your code and `print()` it

```python
cookie_report = f"""
REPORT:
    The total sold is {cookie_total} cookies
    The sold in a day is {cookie_min} cookies
"""
```

In [ ]:
# SOLUTION (NOTES)

cookies = [50,64,45,57,60,84,90]

cookie_total = 0
for c in cookies:
    cookie_total += c

cookie_min = cookies[0]
for c in cookies:
    if c < cookie_min:
        cookie_min = c

cookie_report = f"""
REPORT:
    The total sold is {cookie_total} cookies
    The sold in a day is {cookie_min} cookies
"""

print(cookie_report)

REPORT:
    The total sold is 450 cookies
    The sold in a day is 45 cookies

In [ ]:
# AUTOGRADER
correct_cookie_report = f"""
REPORT:
    The total sold is {sum(cookies)} cookies
    The sold in a day is {min(cookies)} cookies
"""

assert cookie_total == sum(cookies), f"Mistake: check your `cookie_total` it should be {sum(cookies)}"
assert cookie_min == min(cookies)  , f"Mistake: check your `cookie_min` it should be {min(cookies)}"
assert cookie_report == correct_cookie_report, "Mistake: your `cookie_report` must match the format given"

### An introduction to `numpy` and `pandas`

`numpy` and `pandas` are powerful Python libraries which work with two different types of data structures, namely:

- `Numpy` Arrays
- `Pandas` DataFrames

### What is a `numpy` array?

A `numpy` array is a grid of values.

A 1-dimensional array is like a vector of numbers,

```python
array([ 1, -1, -10])
```

A 2-dimensional array is like a simple matrix, similar to a table with columns and rows,

```python
array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])
```

`numpy` arrays can reach as many dimensions as you want.

An n-dimensional array is like a series of matrices stacked on top of one another,

```python
array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]])
```

TEACHER NOTES

More info. for teachers:

"A NumPy array is a type of multi-dimensional data structure in Python which can store objects of similar data types. The elements of the array are indexed by non-negative or positive integers. Arrays are mutable which means arrays can be changed after it is being formed. Arrays are a lot useful for performing mathematical operations on vectors. They provide a lot of useful methods for performing vector operations."

"DataFrame is a two-dimensional, tabular, mutable data structure in Python that can store tabular data containing objects of different data types. A DataFrame has labeled axes in the form of rows and columns. DataFrames are useful tools in data pre-processing as it provides useful methods for data handling.DataFrames are also very useful for creating pivot tables and plotting with Matplotlib."

*Source: https://www.askpython.com/python/pandas-dataframe-vs-numpy-arrays*

### How do I create numpy arrays?

In order to work with numpy arrays, you first need to import `numpy` as follows,

```python
import numpy as np
```

Importing numpy as `np` is a convention.

Then you can use the `np.array()` function to create arrays by providing some data values,  

```python
np.array([1, 2, 3, 4])
```

These data values can be in the form of lists (as shown in the example), tuples, dataframes, and other data forms.

TEACHER NOTES

State that there are other ways to create numpy arrays which the learners will come across later.

#### Challenge: Compare `numpy` arrays with python `lists`

- Run the following code to create a list and a numpy array with the same values:

```python
import numpy as np
ex_list_1 = [10, 20, 30, 40]
ex_list_2 = [40, 30, 20, 10]
ex_array_1 = np.array(ex_list_1)
ex_array_1 = np.array(ex_list_2)
```

- Print both objects. What are the difference in their creation and the way they look after printing?
- Use the `type()` function on each of them. What does it return?

In [ ]:
# SOLUTION (NOTES)

import numpy as np
# Create two lists
ex_list_1 = [10, 20, 30, 40]
ex_list_2 = [40, 30, 20, 10]
ex_array_1 = np.array(ex_list_1)
ex_array_2 = np.array(ex_list_2)

print(ex_list_1)
print(ex_list_2)
print(ex_array_1)
print(ex_array_2)

print(type(ex_list_1))
print(type(ex_list_2))
print(type(ex_array_1))
print(type(ex_array_2))

[10, 20, 30, 40]
[40, 30, 20, 10]
[10 20 30 40]
[40 30 20 10]
<class 'list'>
<class 'list'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

* Why does it matter to convert list to `numpy` array?

In [ ]:

# This throws a TypeError. Lists cannot divide lists.
# cal_two_lists = ex_list_1 * ex_list_2
# This one works
cal_two_lists = ex_list_1 + ex_list_2
print(cal_two_lists) # is that what you expected?

# This one returns you an error
# cal_two_lists = ex_list_1 * ex_list_2

cal_two_arrays = ex_array_1 * ex_array_2
print(cal_two_arrays)

[10, 20, 30, 40, 40, 30, 20, 10]
[400 600 600 400]

### Group Challenge: operating lists and `numpy` arrays

Suppose you have two sets of data
```python
height = [1, 2, 3]
growth = [1, 1, 1]
```

Predict the output of the following operations for both a Python List and a Numpy Array. Then run the code to verify

|   Operation | Python list outcome   |  Numpy array outcome
|:-------|:--------------|:----------------
| `height`+`growth` | ? | ?
| `height`/`growth` | ? | ?
| `height`/2 | ? | ?
| `height`** 2 | ? | ?

#### Challenge: Create a numpy array with `np.array` and get its `.shape`

- Run the following code to create an array:
    ```python
    import numpy as np
    
    arr_1 = np.array([1, 2, 3])
    arr_2 = np.array([[1, 2, 3],
                    [1, 1, 1],
                    [4, 5, 6]])
    
    arr_3 = np.array([[[1, 2, 3],
                    [1, 1, 1],
                    [4, 5, 6]],
                      
                    [[0, 0, 0],
                    [0, 0, 0],
                    [0, 0, 0]]]
                    )
    ```
- Use `arr_1.shape`, `arr_2.shape`, etc. to get the shape of the arrays. What do you get?
- Can

In [ ]:
# SOLUTION (NOTES)

import numpy as np

arr_1 = np.array([1, 2, 3])
arr_2 = np.array([[1, 2, 3],
                 [1, 1, 1],
                 [4, 5, 6]])

arr_3 = np.array([[[1, 2, 3],
                 [1, 1, 1],
                 [4, 5, 6]],

                 [[0, 0, 0],
                 [0, 0, 0],
                 [0, 0, 0]]]
                )

print(arr_1.shape)
print(arr_2.shape)

(3,)
(3, 3)

#### Group Challenge: The broken array
* The broken array
    - The Client sent this data, but the architect says it's impossible to build. Why?
    ```python
    [1,2,3]
    [4,5]
    [7,8,9]
    ```

* Run the following code:
    ```python
        broken_array = np.array([
        [1, 2, 3],
        [4, 5],
        [7, 8, 9]
    ])
    ```
* Why will this crash with a "ValueError"?
* How do you fix it?

In [ ]:
# Write your solution here

### What is a `pandas` DataFrame?

If you imagine a spreadsheet you are imagining something very close to a `pandas` DataFrame.

A `pandas` DataFrame is a two-dimensional grid of values, a table with named columns and rows.

### How do I create a Pandas DataFrame?

In order to work with a Pandas DataFrame, you first need to import `pandas` as follows,

```python
import pandas as pd
```

Importing pandas as `pd` is a convention.

Then you can use the `pd.DataFrame()` function to create DataFrames by providing some data values and column names, below are a couple of examples of how this can be done.  

- Using a dictionary,

```python
pd.DataFrame({'name': ['Alice', 'Bob'],'age': [25, 30]})
```

- Using a list of lists and specifying column names,

```python
pd.DataFrame([['Alice', 25],['Bob', 30]], columns=['name', 'age'])
```

TEACHER NOTES

State that there are other ways to create pandas dataframes which the learners will come across later.

#### Challenge: Compare a DataFrame with an array

- Run the following code. It will create two identical 2-dimensional grids of values. In one case it is a pandas DataFrame. In another one it's a numpy array.

```python
import numpy as np
import pandas as pd
ex_array = np.array([[1, 2, 3],
                  [1, 1, 1],
                  [4, 5, 6]])

ex_df = pd.DataFrame([[1, 2, 3],
                     [1, 1, 1],
                     [4, 5, 6]])

ex_df.columns = ['col_1', 'col_2', 'col_3']

```

- Use the `display()` function on both objects. What's the difference between them?

In [ ]:
# SOLUTION (NOTES)

import numpy as np
import pandas as pd
ex_array = np.array([[1, 2, 3],
                  [1, 1, 1],
                  [4, 5, 6]])

ex_df = pd.DataFrame([[1, 2, 3],
                     [1, 1, 1],
                     [4, 5, 6]])

ex_df.columns = ['col_1', 'col_2', 'col_3']

display(ex_array)
display(ex_df)

array([[1, 2, 3],
       [1, 1, 1],
       [4, 5, 6]])

   col_1  col_2  col_3
0      1      2      3
1      1      1      1
2      4      5      6

---

## Data Processing - implement the ETL process with `pandas`

"Data rarely comes to us clean. In the real world, a Data Scientist spends 60-80% of their time on **ETL** (Extract, Transform, Load). Today we are going to solve the specific pain points that cause Python scripts to crash."



### 1.1 Import Libraries

In [ ]:
import pandas as pd
import numpy as np
import math
import time

# Optional: Adjust display settings to see more columns/rows
pd.set_option('display.max_columns', None)
print("Libraries imported successfully.")

Libraries imported successfully.

---

### Extract: Ingesting "Wild" Data Types

You may already know `pd.read_csv('file.csv')`. I am going to show you what happens when files are messy.

**What is done**: We are moving away from the simple pd.read_csv('clean_file.csv') command. Instead, we are using advanced parameters like `sep='|'` , `encoding='latin-1'`, and `skiprows=2` to force Python to read files that are formatted incorrectly for standard tools.

**Why it matters**: In the real world, data never arrives clean. It comes from legacy systems (which use weird separators), international teams (different encodings), or Excel reports meant for humans (with "titles" in the first few rows). If you don't know these parameters, your script crashes immediately, and you cannot start your job.

### 1 The CSV (Comma Separated Values)
**The problem:** The file `raw_sales.csv` uses pipes `|` instead of commas and has `latin-1` encoding (common in Excel exports on Windows).

In [ ]:
# COMMON ERROR: This will fail
# df = pd.read_csv('raw_sales.csv')

**Solution** Specifiy separator and encoding

In [ ]:
# SOLUTION: Specify separator and encoding
try:
    df_csv = pd.read_csv('raw_sales.csv', sep='|', encoding='latin-1')
    print("CSV Loaded Successfully:")
    display(df_csv.head())
except FileNotFoundError:
    print("File not found. Please ensure 'raw_sales.csv' is in the working directory.")

CSV Loaded Successfully:

    ID     Revenue           Date  Target
0  101  $12,000.00     2023-01-01   100.0
1  102     $500.50     01/02/2023     NaN
2  103         200  2023-March-05   150.0
3  104   $1,200.00     2023-01-01     NaN
4  105  $15,500.25     2023-04-10   200.0

### 2 The Excel File (.xlsx)
**The problem:**
Excel reports often have titles, dates, or logos in the first few rows. Pandas assumes the first row (Row 0) is the header.

**Example**
`targets.xlsx` has a "Report Title" in the first 2 rows. The actual header is on Row 3.

**Solution**
We use `skiprows` in `read_excel()` to adjust

In [ ]:
# Use read_excel to load the Excel file
# Specify the sheet name if necessary
df_excel = pd.read_excel('targets.xlsx', sheet_name='Q1_Targets')
print("Excel Loaded Successfully:")
display(df_excel.head())

Excel Loaded Successfully:

  CONFIDENTIAL INTERNAL REPORT Unnamed: 1 Unnamed: 2
0        Generated: 2023-01-01        NaN        NaN
1                       Region  Q1_Target    Manager
2                        North      50000      Alice
3                        South      60000        Bob
4                         East      45000    Charlie

In [ ]:
# SOLUTION: Use skiprows=2 (skips row 0 and 1, reads from row 2)
try:
    df_excel = pd.read_excel('targets.xlsx', sheet_name='Q1_Targets', skiprows=2)
    print("Excel Loaded Successfully:")
    display(df_excel.head())
except ImportError:
    print("Error importing files")

Excel Loaded Successfully:

  Region  Q1_Target  Manager
0  North      50000    Alice
1  South      60000      Bob
2   East      45000  Charlie
3   West      70000     Dana

### 3 JSON

You may already know `pd.read_json('file.json')`. I am going to show you what happens when files are messy.

**The problem:** JSON often contains nested dictionaries.

In [ ]:
try:
    df_json = pd.read_json('user_logs.json')
    print("JSON Loaded (Notice the nested 'details' column):")
    display(df_json.head(2))
except ValueError:
    print("JSON load failed.")

JSON Loaded (Notice the nested 'details' column):

   user_id   name                                details
0        1  Alice  {'login_count': 5, 'plan': 'premium'}
1        2    Bob     {'login_count': 1, 'plan': 'free'}

* Notice 'details' is a single column with {dicts} inside. How could we fix it ?

##### We can flatten the dataframe using `pd.json_normalize()`

In [ ]:
import pandas as pd
import json

# 1. Load the raw data to see the problem
# Notice 'details' is a single column with {dicts} inside
with open('user_logs.json', 'r') as f:
    raw_json = json.load(f)

print("--- Raw JSON Structure (Nested) ---")
print(raw_json[0])

# The Fix: json_normalize
# This function "flattens" the nested keys into new columns using dot notation
df_flat = pd.json_normalize(raw_json)

print("\n--- Flattened DataFrame ---")
display(df_flat)
# Result:
# user_id | name    | details.login_count | details.plan
# 1       | Alice   | 5                   | premium

--- Raw JSON Structure (Nested) ---
{'user_id': 1, 'name': 'Alice', 'details': {'login_count': 5, 'plan': 'premium'}}

--- Flattened DataFrame ---

   user_id     name  details.login_count details.plan
0        1    Alice                    5      premium
1        2      Bob                    1         free
2        3  Charlie                   10      premium

---

### The SOP: Standard Operating Procedure for Cleaning

**Note:** Stop here. Stress that **loading != ready**.
Do NOT jump to analysis yet. We must pass the **SOP Checklist**:
1.  **Health Check:** `.info()`
2.  **Clean Headers:** Standardize names.
3.  **Type Enforcement:** Fix "Objects".
4.  **Null Handling:** Detect and Fill.

---


##### What is done:
We are implementing a rigid "Standard Operating Procedure" (SOP). This involves checking `.info()` immediately, stripping currency symbols `($, ,)` from numbers, forcing columns into float or datetime formats, and making a conscious decision about how to fill missing values `(NaN)`.

---

##### Why it matters:

This prevents "Silent Failures." A column containing "$1,000" looks like a number to a human, but Python sees it as a text string (Object). If you try to calculate the average revenue on this column, Python might just concatenate the strings or crash later in a machine learning model. Cleaning before analysis is the only way to trust your results.

---

#### Step 1: The Health Check

In [ ]:
# Check types. Notice 'Revenue' is an object (string) because of the '$' sign.
print("--- Data Info ---")
df_csv.info()

--- Data Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   ID       6 non-null      int64
 1   Revenue  6 non-null      object
 2   Date     6 non-null      object
 3   Target   3 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 324.0+ bytes

* Check types. Notice 'Revenue' is an object (string) because of the '$' sign.

####  Step 2: Cleaning Headers
Spaces in column names are annoying. Let's make them `snake_case`.

In [ ]:
df_csv.head()

    ID     Revenue           Date  Target
0  101  $12,000.00     2023-01-01   100.0
1  102     $500.50     01/02/2023     NaN
2  103         200  2023-March-05   150.0
3  104   $1,200.00     2023-01-01     NaN
4  105  $15,500.25     2023-04-10   200.0

In [ ]:
# Strip whitespace and convert to lower case
df_csv.columns = df_csv.columns.str.strip().str.lower()
print("Cleaned Columns:", df_csv.columns.tolist())

Cleaned Columns: ['id', 'revenue', 'date', 'target']

#### Step 3: Type Enforcement (String to Float)
**Task:** Convert `$12,000.00` (String) -> `12000.0` (Float).

In [ ]:
# 1. Access the string accessor (.str)
# 2. Replace symbols ($ and ,)
# 3. Cast to float (.astype)

df_csv['revenue'] = df_csv['revenue'].astype(str).str.replace('$', '', regex=False).str.replace(',', '', regex=False)
df_csv['revenue'] = df_csv['revenue'].astype(float)

print("Revenue Converted:")
display(df_csv[['revenue']].head())
print("New Type:", df_csv['revenue'].dtype)

Revenue Converted:

    revenue
0  12000.00
1    500.50
2    200.00
3   1200.00
4  15500.25

New Type: float64

#### Step 4: DateTime Conversion
**The problem:** There are mixed date formats (`2023-01-01` vs `01/02/2023`) in the dataframe

**Solution:** Use `pd.to_datetime()` to fix it

In [ ]:

# errors='coerce' turns unparseable data into NaT (Not a Time) instead of crashing
df_csv['date'] = pd.to_datetime(df_csv['date'], format='mixed', errors='coerce')

print("Dates Converted:")
display(df_csv[['date']].head())

Dates Converted:

        date
0 2023-01-01
1 2023-01-02
2 2023-03-05
3 2023-01-01
4 2023-04-10

#### Step 5: Handling Missing Data (Imputation)
**The problem:** the column `Target` has missing values.

**Solution**

1. We can impute the missing values with different measures `.fillna()`
2. We can delete rows where ANY column is missing `.dropna()`
3. We can delete rows only if a specific column is missing `.dropna(subset=[''])`
4. We can replace with constant fill

In [ ]:
print("Missing Values Before:")
print(df_csv.isna().sum())

# Option A: Delete rows where ANY column is missing
df_clean = df_csv.dropna()

# Option B: Delete rows only if a SPECIFIC column is missing
# (e.g., delete rows with no 'target', but keep rows)
df_clean = df_csv.dropna(subset=['target'])

# Calculate mean (ignoring NaNs automatically)
mean_val = df_csv['target'].mean()

# Fill NaNs
df_csv['target'] = df_csv['target'].fillna(mean_val)

print(f"\nMissing Values After (Filled with {mean_val}):")
print(df_csv.isna().sum())

Missing Values Before:
id         0
revenue    0
date       3
target     3
dtype: int64

Missing Values After (Filled with 150.0):
id         0
revenue    0
date       3
target     0
dtype: int64

### Key Takeaways

**1. Real-World Data is "Wild"**
Standard functions like `pd.read_csv()` often fail on real business data. You now know how to handle:
* **Encoding Errors:** Switching to `latin-1` when standard UTF-8 fails.
* **Bad Delimiters:** Handling pipes `|` or tabs instead of commas.
* **Metadata Rows:** Using `skiprows` to bypass report headers in Excel.

**2. The Cleaning SOP is Non-Negotiable**
We introduced the **Standard Operating Procedure (SOP)** to prevent "Silent Failures":
* **Health Check:** Always run `.info()` first to spot the "Object Trap" (numbers hidden as strings).
* **Type Enforcement:** You must explicitly cast columns to `float` or `datetime`. Python will not guess for you.
* **Null Strategy:** Never blindly drop data. Decide whether to Drop, Fill with Mean, or Flag missing values.