<img src=https://courseware.decoded.com/images/decoded/logo-decoded.png align=left width=100px/>

# Python: Further Data Manipulation

---

<small>© COPYRIGHT 2026 DECODED LIMITED. ALL RIGHTS RESERVED. Web: https://decoded.com/ </small>

## Learning Objectives

1. **Series** Understanding Series as the building blocks of Dataframes and their behaviour
2. **Loc vs Iloc:** Understanding the problems that occur from inconsistent indexing and how .iloc and loc fix it
3. **Conditional Filtering:** Learning how to apply a variety of filter conditions to extract specific columns and rows based a on a condition
4. **Aggregating Data** Learn how to quickly wrangle data with aggregates
5. **Introduction To Functions** Discover how functions are used in the context of Data Science and learn some write some yourself


---



### Programmes

* Workshop 1.2 - Data Science Accelerator

###Workshop Summary

This chapter will expand upon the first session introducing key techniques used in data manipulation from indexing to aggregation and introducing the idea of data preprocessing



*   What is advanced data manipulation in Python?
    *   What does “data manipulation” mean beyond basic cleaning?
    *   How does pandas build on Python fundamentals?
    *   When should I think in rows, columns, or vectors?
*   Working with `pandas.Series`
    *   What is a `Series` and how does it differ from a list?
    *   How do indexing and slicing work in a `Series`?
    *   How can a `Series` behave like:
        *   a dictionary (key–value access)
        *   a NumPy array (vectorised operations)
*   Label-based vs position-based indexing
    *   What problem do `.loc` and `.iloc` solve?
    *   How do labels differ from integer positions?
    *   How do you safely subset data using:
        *   row labels
        *   column labels
        *   row/column positions
*   Conditional filtering in pandas
    *   How do you filter data using boolean conditions?
    *   How do comparison operators work on entire columns?
    *   How do you combine multiple conditions correctly?
    *   Why is conditional filtering foundational for analysis?
*   Aggregating data with pandas
    *   What does aggregation mean in data analysis?
    *   How do you summarise data using:
        *   `sum`, `mean`, `count`, `min`, `max`
    *   How does aggregation change the “shape” of data?
    *   When do you aggregate before vs after filtering?
*   Performant data manipulation with NumPy
    *   Why performance matters for large datasets
    *   What is vectorisation and why is it faster than loops?
    *   How NumPy executes operations at scale
    *   Comparing:
        *   Python loops
        *   NumPy vectorised operations
*   Functions for data preprocessing
    *   Why repeated preprocessing logic is a problem
    *   How functions improve:
        *   reusability
        *   readability
        *   consistency
    *   Encapsulating data-cleaning logic into functions
*   Limitations of ad-hoc preprocessing
    *   Why “one-off” cleaning code does not scale
    *   Common problems with:
        *   copy-paste logic
        *   hidden assumptions
        *   fragile pipelines
    *   The need for structured, repeatable preprocessing
*   Review
    *   What did we learn?
    *   How pandas and NumPy fit together in practice
    *   How this prepares you for feature engineering and machine learning
*   What should I learn next?
    *   GroupBy operations and split-apply-combine
    *   Feature engineering patterns
    *   Data validation and schema enforcement
    *   Preprocessing with scikit-learn pipelines

### Applications: Why study Data Processing in Python?

This section set up the foundational knowledge needed to work directly with data in python and introduces concepts and practices that support the ingestion phase of a ML pipelline

## Data Manipulation - `Series` Slicing & Index

---

## Series as a dictionary

below we can see that the a series behaves similary to a standard dictionary

In [ ]:
# series contains the lovely features of vectorisation
import pandas as pd
data = pd.Series([1,2,3,4,5,6,7],index=['jan','feb','mar','apr','may','jun','jul'],name="Monthly Sales")

In [ ]:
data

jan    1
feb    2
mar    3
apr    4
may    5
jun    6
jul    7
Name: Monthly Sales, dtype: int64

In [ ]:
data+5

jan     6
feb     7
mar     8
apr     9
may    10
jun    11
jul    12
Name: Monthly Sales, dtype: int64

In [ ]:
data['jan']

np.int64(1)

In [ ]:
'jan' in data

True

In [ ]:
data.keys()

Index(['jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul'], dtype='object')

In [ ]:
list(data.items())

[('jan', 1),
 ('feb', 2),
 ('mar', 3),
 ('apr', 4),
 ('may', 5),
 ('jun', 6),
 ('jul', 7)]

In [ ]:
data['aug']= 8

### Series as a Numpy array

Here we will show that a series can be indexed in a way similar to numpy array as seen in the previous session

In [ ]:
data['jan':'mar']  # Slicing by index labels

jan    1
feb    2
mar    3
dtype: int64

In [ ]:
data[0:3]

jan    1
feb    2
mar    3
dtype: int64

In [ ]:
data[['jan','aug']]

jan    1
aug    8
dtype: int64

---

# Data Manipulation - .loc and .iloc

---

Here we will uncover the inconsistency in python that motivates the need for loc and iloc

In [ ]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data

1    a
3    b
5    c
dtype: object

Example

In [ ]:
[1,   3,   5] #label
['a','b','c'] #values
[ 0 , 1 , 2 ] #positional index

[1:3]-># return elems at positions [1,2]

in the cell we can see that it used the exact index

In [ ]:
data[1]
#the above

'a'

Lets see what happens when we slice it

In [ ]:
data[1:3]

3    b
5    c
dtype: object

we expected indexes 1,2 which should have been a and b but got the b and c instead!

Chose either for consistency! loc or iloc!

In [ ]:

data.loc[1]

'a'

In [ ]:
data.loc[1:3]

1    a
3    b
dtype: object

iloc = position

In [ ]:
data.iloc[1]

'b'

In [ ]:
data.iloc[1:3]

3    b
5    c
dtype: object

In [ ]:
import pandas as pd

s = pd.Series(
    data=range(20),        # values: 0–19
    index=range(0, 40, 2)  # index: 0, 2, 4, ..., 38
)

s

s.iloc[1:10]

2     1
4     2
6     3
8     4
10    5
12    6
14    7
16    8
18    9
dtype: int64

In [ ]:
s.loc[1:10]

2     1
4     2
6     3
8     4
10    5
dtype: int64

which to use - indexed

Dates / timestamps
User IDs
Transaction IDs
Filtered or resampled remnants

if they are meaningful yes - e.g. time series
if not random - columns

---

# Data Manipulation - Conditional Filtering

---

# Select all rows where region is London

In [11]:
df = pd.DataFrame({
    "order_id": [101, 102, 103, 104, 105, 106, 107, 108],
    "region": [
        "London", "London", "Manchester", "London",
        "Birmingham", "Manchester", "London", "Birmingham"
    ],
    "category": [
        "Food", "Tech", "Food", "Food",
        "Tech", "Food", "Tech", None
    ],
    "sales": [1200, 800, 400, 1500, 2000, 300, 500, 900],
    "cost":  [700, 900, 300, 600, 1200, 350, 600, 400]
})

In [ ]:

df[df["region"] == "London"]

   order_id  region category  sales  cost
0       101  London     Food   1200   700
1       102  London     Tech    800   900
3       104  London     Food   1500   600
6       107  London     Tech    500   600

# Select all rows where cost is greater than 500

In [ ]:

df[df["cost"] > 500]

   order_id      region category  sales  cost
0       101      London     Food   1200   700
1       102      London     Tech    800   900
3       104      London     Food   1500   600
4       105  Birmingham     Tech   2000  1200
6       107      London     Tech    500   600

# Select all rows where cost is greater than 600 and region is London

In [12]:

df[df["cost"] > 600 & df["region"] == "London"]

TypeError: Cannot perform 'rand_' with a dtyped [object] array and scalar of type [bool]

# Select all rows where region is either London, Manchester or France

In [ ]:

df[df["region"].isin(["London", "Manchester","France"])]

   order_id      region category  sales  cost
0       101      London     Food   1200   700
1       102      London     Tech    800   900
2       103  Manchester     Food    400   300
3       104      London     Food   1500   600
5       106  Manchester     Food    300   350
6       107      London     Tech    500   600

# Select all rows where category is missing

In [ ]:

df[df["category"].isna()]

   order_id      region category  sales  cost
7       108  Birmingham     None    900   400

# Select all rows where category contains 'ec' (case insensitive)

In [ ]:

df[df["category"].str.contains("ec", case=False, na=False)]

   order_id      region category  sales  cost
1       102      London     Tech    800   900
4       105  Birmingham     Tech   2000  1200
6       107      London     Tech    500   600

# Aggregating Data With Pandas

---

## Why do we need aggregation?

We aggregate data because **decisions are almost never made at the row level**.  
Instead, we ask higher-level questions such as:

- How much **revenue** did we make per day?
- Which **category** performs best?
- What is the **average order value** by customer or channel?
- How do outcomes differ across **locations** or **time periods**?

---

### What aggregation helps us do

Aggregation allows us to:

- **Reduce noise**  
  Summarise thousands of rows into a few clear, meaningful numbers

- **Compare groups**  
  Spot differences between categories, regions, or time windows

- **Identify patterns and trends**  
  Especially when aggregating over time

- **Prepare data for visualisation and modelling**  
  Most charts and models rely on aggregated inputs

---

In [ ]:
# Data question: What does our raw transactional dataset look like before any summarisation?
import pandas as pd

df = pd.DataFrame(
    {
        "order_id":  [1001,1002,1003,1004,1005,1006,1007,1008,1009,1010],
        "date":      pd.to_datetime(["2026-01-02","2026-01-02","2026-01-03","2026-01-03","2026-01-04",
                                     "2026-01-04","2026-01-05","2026-01-05","2026-01-06","2026-01-06"]),
        "customer":  ["C001","C002","C001","C003","C004","C002","C005","C001","C003","C006"],
        "city":      ["London","London","London","Manchester","Manchester","London","Birmingham","London","Manchester","Birmingham"],
        "category":  ["Coffee","Coffee","Tea","Coffee","Tea","Tea","Coffee","Coffee","Tea","Coffee"],
        "qty":       [2,1,3,1,2,1,4,1,2,1],
        "unit_price":[3.50,3.50,2.40,3.50,2.40,2.40,3.50,3.50,2.40,3.50],
    }
)

df["revenue"] = df["qty"] * df["unit_price"]
df

   order_id       date customer        city category  qty  unit_price  revenue
0      1001 2026-01-02     C001      London   Coffee    2         3.5      7.0
1      1002 2026-01-02     C002      London   Coffee    1         3.5      3.5
2      1003 2026-01-03     C001      London      Tea    3         2.4      7.2
3      1004 2026-01-03     C003  Manchester   Coffee    1         3.5      3.5
4      1005 2026-01-04     C004  Manchester      Tea    2         2.4      4.8
5      1006 2026-01-04     C002      London      Tea    1         2.4      2.4
6      1007 2026-01-05     C005  Birmingham   Coffee    4         3.5     14.0
7      1008 2026-01-05     C001      London   Coffee    1         3.5      3.5
8      1009 2026-01-06     C003  Manchester      Tea    2         2.4      4.8
9      1010 2026-01-06     C006  Birmingham   Coffee    1         3.5      3.5

# Data question: How many orders do we have in each city?

In [ ]:

df.groupby("city")["order_id"].count()

city
Birmingham    2
London        5
Manchester    3
Name: order_id, dtype: int64

# Data question: What is the total revenue generated in each city?

In [ ]:

df.groupby("city")["revenue"].sum()

city
Birmingham    17.5
London        23.6
Manchester    13.1
Name: revenue, dtype: float64

# Data question: What is the average order revenue in each city?

In [ ]:

df.groupby("city")["revenue"].mean()

city
Birmingham    8.750000
London        4.720000
Manchester    4.366667
Name: revenue, dtype: float64

# Data question: What is the smallest (minimum) order revenue we see in each city?

In [ ]:

df.groupby("city")["revenue"].min()

city
Birmingham    3.5
London        2.4
Manchester    3.5
Name: revenue, dtype: float64

# Data question: What is the largest (maximum) order revenue we see in each city?

In [ ]:

df.groupby("city")["revenue"].max()

city
Birmingham    14.0
London         7.2
Manchester     4.8
Name: revenue, dtype: float64

# Data question: What is the typical order revenue in each city (less sensitive to outliers than the mean)?

In [ ]:

df.groupby("city")["revenue"].median()

city
Birmingham    8.75
London        3.50
Manchester    4.80
Name: revenue, dtype: float64

# Data question: How consistent are order revenues in each city (i.e., how much do they vary)?

In [ ]:

df.groupby("city")["revenue"].std()

city
Birmingham    7.424621
London        2.219685
Manchester    0.750555
Name: revenue, dtype: float64

# Introducing `.agg()` — combining multiple aggregates

So far, each aggregation has answered **one question at a time**  
(e.g. `count`, `sum`, `mean`).

In real data analysis, we usually want **several summary metrics together**.

---

### What does `.agg()` do?

The `.agg()` method allows us to:

- Apply **multiple aggregate functions at once**
- Give **clear names** to each aggregated output
- Produce **one tidy summary table** instead of many separate ones

In [ ]:
# Data question: For each city, how many orders are there and how much total revenue is generated?

df.groupby("city").agg(
    orders=("order_id", "count"),
    total_revenue=("revenue", "sum"),
)

            orders  total_revenue
city
Birmingham       2           17.5
London           5           23.6
Manchester       3           13.1

In [ ]:
# Data question: How does the typical order compare to the average order in each city?

df.groupby("city").agg(
    avg_order_value=("revenue", "mean"),
    median_order_value=("revenue", "median"),
)

            avg_order_value  median_order_value
city
Birmingham         8.750000                8.75
London             4.720000                3.50
Manchester         4.366667                4.80

In [ ]:
# Data question: For each city, how many unique customers do we have and
# what is the highest single-order revenue recorded?

df.groupby("city").agg(
    customers=("customer", "nunique"),
    max_order_value=("revenue", "max"),
)

            customers  max_order_value
city
Birmingham          2             14.0
London              2              7.2
Manchester          2              4.8

---

## Performant Data Manipulation With Numpy

In standard Python, we use `for` loops. In Data Science, looping over 10 million rows is too slow. Here we introduce numpy and show the improvements from  **Vectorization**."

---

### 1 Vectorized Math vs. Loops
**Scenario:** Calculate the Natural Log `ln()` of revenue.

##### Generate big data for the test (1 Million Rows)

In [ ]:
import numpy as np
import pandas as pd
import time
import math
import numexpr

# Generate big data for the test (10 Million Rows)
big_data = np.random.rand(100000000) * 1000
df_big = pd.DataFrame({'revenue': big_data})
df_big.head(5)

      revenue
0  466.296986
1  421.484404
2  356.774719
3   41.782558
4  885.486241

In [ ]:
big_data.shape

(100000000,)

#### Method 1: The Loop

In [ ]:
start = time.time()
res = []
for x in df_big['revenue']:
    res.append(math.log(x))
end = time.time()
print(f"Loop Time: {end - start:.4f} seconds")

Loop Time: 6.2849 seconds

##### Method 2: Numpy Vectorization

In [ ]:
# --- APPROACH 2: Numpy Vectorization (Fast) ---
start = time.time()
df_big['log_revenue'] = np.log(df_big['revenue'])
end = time.time()
print(f"Numpy Time: {end - start:.4f} seconds")

# Instructor Note: Point out that Numpy is usually 50-100x faster.

Numpy Time: 0.3173 seconds

Another Example Adding Elements Of Two Arrays

In [ ]:
start = time.time()
rng = np.random.default_rng(42)
x = rng.random(1000000)
y = rng.random(1000000)
end = time.time()
print(f"Numpy Time: {end - start:.4f} seconds")

Numpy Time: 0.0137 seconds

In [ ]:
start = time.time()
np.fromiter((xi + yi for xi, yi in zip(x, y)),dtype=x.dtype, count=len(x))
end = time.time()
print(f"Numpy Time: {end - start:.4f} seconds")

Numpy Time: 0.0778 seconds

---

# FUNCTIONS FOR DATA PREPROCESSING

---

## Why do we need functions?

Before introducing functions, it’s important to understand **the problem they are solving**.

In real data work — especially during **data preprocessing** — you will often:

- Clean **multiple columns in the same way**
- Copy and paste **working code** to move faster
- Make **small tweaks** as requirements evolve

At first, this approach feels efficient.

---

### The hidden problem

As your dataset grows and your logic changes, this pattern quietly introduces risks:

- Repeated logic becomes **hard to update**
- Small changes can lead to **inconsistent behaviour**
- Bugs are more likely to appear in **only some places**

---

### Why this example is written this way

This example is written for you as a **data analyst transitioning toward data science**.

It deliberately **starts by repeating code**, so you can:

- Clearly see the **pain points**
- Feel why the approach stops scaling
- Understand **why functions exist**, before learning how to write them

# EXAMPLE

In [ ]:
import pandas as pd
import numpy as np

# Simulated raw data
df = pd.DataFrame({
    "city_a": [" London ", "PARIS", None, "  berlin"],
    "city_b": [" madrid", None, "ROME ", " Lisbon"],
    "city_c": [None, " ATHENS", "vienna ", "  Prague"]
})

df

     city_a   city_b    city_c
0   London    madrid      None
1     PARIS     None    ATHENS
2      None    ROME    vienna
3    berlin   Lisbon    Prague

Repeating the Same Cleaning Logic (❌ Not Scalable)

In [ ]:
# Clean city_a
df["city_a"] = (
    df["city_a"]
    .fillna("unknown")
    .str.strip()
    .str.lower()
)

# Clean city_b
df["city_b"] = (
    df["city_b"]
    .fillna("unknown")
    .str.strip()
    .str.lower()
)

# Clean city_c
df["city_c"] = (
    df["city_c"]
    .fillna("unknown")
    .str.strip()
    .str.lower()
)

df

    city_a   city_b   city_c
0   london   madrid  unknown
1    paris  unknown   athens
2  unknown     rome   vienna
3   berlin   lisbon   prague


# Problems with this approach

- Code duplication
- Hard to maintain (change logic in 3 places)
- Easy to introduce inconsistencies

# Functional approach

In [ ]:
def clean_text_column(series: pd.Series) -> pd.Series:
    return (
        series
        .fillna("unknown")
        .str.strip()
        .str.lower()
    )

In [ ]:
for col in ["city_a", "city_b", "city_c"]:
    df[col] = clean_text_column(df[col])

df

    city_a   city_b   city_c
0   london   madrid  unknown
1    paris  unknown   athens
2  unknown     rome   vienna
3   berlin   lisbon   prague

# Why does this matter?

- Single source of truth for preprocessing logic

- Easier experimentation (change once, apply everywhere)

- Functions compose cleanly into pipelines later (e.g. sklearn)

- Clear boundary between what you do and where you do it

- This is the first step toward reproducible, testable preprocessing pipelines.

# Function Syntax

In [ ]:
def function_name(parameter1, parameter2):
    """Optional description of what the function does."""
    # function body (indented)
    result = parameter1 + parameter2
    return result

## Python Function Anatomy

**def**  
- Short for *define*  
- Tells Python you are creating a function  

**function_name**  
- How you refer to and call the function later  
- Should describe what the function does  

**(parameter1, parameter2)**  
- Parameters are inputs to the function  
- Both inputs must be provided when calling the function  

**:**  
- Marks the start of the function body  

**Indentation**  
- Everything indented underneath belongs to the function  
- This is how Python knows what code is inside the function  

**return**  
- Sends a value back to where the function was called  
- Ends the function immediately

# Function Examples

#one input, one output

In [ ]:


def double(number):
    return number * 2

double(4)

8

#the same function can be reused with different values

In [ ]:


def add_exclamation(text):
    return text + "!"

add_exclamation("hello")
add_exclamation("great")
add_exclamation("wow")

#a function can accept more than one input

In [ ]:

def full_name(first, last):
    return first + " " + last

full_name("Ada", "Lovelace")

#parameters can have default values

In [ ]:


def greet(name, greeting="Hello"):
    return greeting + ", " + name

greet("Sam")
greet("Sam", greeting="Hi")

#without return, the function returns None

In [ ]:
def announce(message):
    print(message)

result=announce("Starting program")
print(result)

Starting program
None